# Generated by Django 5.0.7 on 2024-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_electoralroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanCardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_father_name', models.CharField(max_length=255)),
                ('applicant_dob', models.DateField()),
                ('applicant_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('applicant_aadhaar', models.CharField(max_length=12, unique=True)),
                ('applicant_address', models.TextField()),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_contact', models.CharField(max_length=15)),
                ('id_proof', models.FileField(upload_to='documents/id_proof/')),
                ('address_proof', models.FileField(upload_to='documents/address_proof/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/supporting_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
