# Generated by Django 5.0.7 on 2024-11-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pancardapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('deceased_dob', models.DateField()),
                ('deceased_dod', models.DateField()),
                ('deceased_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('deceased_aadhaar', models.CharField(max_length=12)),
                ('deceased_address', models.TextField()),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_relation', models.CharField(max_length=255)),
                ('applicant_address', models.TextField()),
                ('applicant_contact', models.CharField(max_length=15)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
